export {
  assinaturaPlataformaPremiumAtiva,
  assinaturaPremiumAtiva,
  creatorMembershipDoAutorAtiva,
  creatorMembershipAtiva,
  algumaMembershipDeCriadorAtiva,
  algumaCreatorMembershipAtiva,
  listarMembershipsDeCriadorAtivas,
  usuarioTemPapelAdminPlataforma,
  podeLerCapituloAntecipado,
  usuarioTemAcessoAntecipado,
  resolverCreatorIdDoCapitulo,
  capituloLiberadoParaUsuario,
  podeUsarAvataresPremiumDaLoja,
  descontoVipLojaAtivo,
  obterUserEntitlements,
  obterEntitlementPremiumGlobal,
  obterEntitlementCriador,
} from './entitlementsClean';
